<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RequestDemo_btn</name>
   <tag></tag>
   <elementGuidId>23e52003-0ce9-45b1-adfb-f948fd1fbbfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div[1]/div[2]/div/div/div[1]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div[1]/div[2]/div/div/div[1]/div/div/button</value>
   </webElementProperties>
</WebElementEntity>
