<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VerifDemo_Page</name>
   <tag></tag>
   <elementGuidId>7874ff58-8c62-4c6d-a440-866a9bea9421</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div[1]/div[2]/div/div/div[1]/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div[1]/div[2]/div/div/div[1]/div/div/p</value>
   </webElementProperties>
</WebElementEntity>
